export default{
    Browse_options:[
        { value: 'anime', label: 'Anime' },
        { value: 'manga', label: 'Manga' },
        { value: 'characters', label: 'Characters' },
        { value: 'staff', label: 'Staff' },
        { value: 'studios', label: 'Studios' },
        { value: 'users', label: 'Users' },
      ],
      Genres_options : [
        { value: 'action', label: 'Action' },
        { value: 'adventure', label: 'Adventure' },
        { value: 'comedy', label: 'Comedy' },
        { value: 'drama', label: 'Drama' },
        { value: 'ecchi', label: 'Ecchi' },
        { value: 'fantasy', label: 'Fantasy' },
        { value: 'horror', label: 'Horror' },
        { value: 'mahou-shoujo', label: 'Mahou Shoujo' },
        { value: 'mecha', label: 'Mecha' },
        { value: 'music', label: 'Music' },
        { value: 'mystery', label: 'Mystery' },
        { value: 'psychological', label: 'Psychological' },
        { value: 'romance', label: 'Romance' }
      ],
      Season_options : [
        { value: 'winter', label: 'Winter' },
        { value: 'spring', label: 'Spring' },
        { value: 'summer', label: 'Summer' },
        { value: 'fall', label: 'Fall' },
      ],
      Format_options : [
        { value: 'tv-show', label: 'TV Show' },
        { value: 'movie', label: 'Movie' },
        { value: 'tv-short', label: 'TV Short' },
        { value: 'special', label: 'Special' },
        { value: 'ova', label: 'OVA' },
        { value: 'ona', label: 'ONA' },
        { value: 'music', label: 'Music' },
      ],
      Airing_status_options : [
        { value: 'airing', label: 'Airing' },
        { value: 'finished', label: 'Finished' },
        { value: 'not_yet_aired', label: 'Not Yet Aired' },
        { value: 'cancelled', label: 'Cancelled' },
      ],
      Streaming_on_options : [
        { value: 'crunchyroll', label: 'Crunchyroll' },
        { value: 'funimation', label: 'Funimation' },
        { value: 'hidive', label: 'Hidive' },
        { value: 'vrv', label: 'VRV' },
        { value: 'netflix', label: 'Netflix' },
        { value: 'amazon', label: 'Amazon' },
        { value: 'hulu', label: 'Hulu' },
        { value: 'hbo_max', label: 'HBO Max' },
        { value: 'animelab', label: 'AnimeLab' },
        { value: 'viz', label: 'Viz' },
        { value: 'adult_swim', label: 'Adult Swim' },
        { value: 'retrocrush', label: 'RetroCrush' },
        { value: 'midnight_pulp', label: 'Midnight Pulp' },
        { value: 'tubi_tv', label: 'Tubi TV' },
        { value: 'contv', label: 'CONtv' },
      ],
      Country_options : [
        { value: 'japan', label: 'Japan' },
        { value: 'south_korea', label: 'South Korea' },
        { value: 'china', label: 'China' },
        { value: 'taiwan', label: 'Taiwan' },
      ],
      Format_options : [
        { value: 'TV', label: 'TV Show' },
        { value: 'south_korea', label: 'Movie' },
        { value: 'china', label: 'TV Short' },
        { value: 'china', label: 'Special' },
        { value: 'china', label: 'OVA' },
        { value: 'china', label: 'ONA' },
        { value: 'china', label: 'Music' }
      ],
      source_material_options : [
        { value: 'original', label: 'Original' },
        { value: 'manga', label: 'Manga' },
        { value: 'light_novel', label: 'Light Novel' },
        { value: 'anime', label: 'Anime' },
        { value: 'visual_novel', label: 'Visual Novel' },
        { value: 'video_game', label: 'Video Game' },
        { value: 'doujinshi', label: 'Doujinshi' },
        { value: 'other', label: 'Other' },
      ],
      some_array:[
        {value:"some1", label:"something1"},
        {value:"some2", label:"something2"},
      ]
}